export const TrainingActionTypes = {
    SET_TRAINING: 'SET_TRAINING',
    ADD_TRAINING: 'ADD_TRAINING',
    RESET_TRAINING: 'RESET_TRAINING',
    SET_TRAINING_BY_PACKAGE: 'SET_TRAINING_BY_PACKAGE',
    SET_TRAINING_ONLY_SELF: 'SET_TRAINING_ONLY_SELF',
    SET_TRAINING_NO_SELF: 'SET_TRAINING_NO_SELF',
    SET_DESCRIPTIONS: 'SET_DESCRIPTIONS'
};